### PR TITLE
fix: waitUntilReady in applyStep now uses the correct namespace/project.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by davidkuster** [comment]
@iocanel thanks for fixing this. Can you verify, is this the same error you were seeing, when presumably attempting to target a namespace that wasn't `default`?

```
ERROR: Error during kubernetes apply: io.fabric8.kubernetes.client.KubernetesClientTimeoutException: 
Timed out waiting for [<millis value>] milliseconds for multiple resources. 
Resources that are not ready: [Kind:Deployment Name:<deployment-name> Namespace:default]
```

**Comment by iocanel** [comment]
@davidkuster: Yes!

**Comment by davidkuster** [comment]
@iocanel thanks! I see you merged this into master, which is awesome. Question though - do you know how to have this change picked up by the [fabric8-pipeline-library](https://github.com/fabric8io/fabric8-pipeline-library)? I'm a bit fuzzy on how the dependencies between these projects work. In that [pom](https://github.com/fabric8io/fabric8-pipeline-library/blob/master/pom.xml#L262) I see:
```
    <dependency>
      <groupId>org.csanchez.jenkins.plugins</groupId>
      <artifactId>kubernetes</artifactId>
      <version>0.12</version>
    </dependency>
```
Which might be a pointer to this plugin, although from what I can tell that version number seems extremely old.

Any tips pointing me in the right direction would be much appreciated. Again, thanks!

**Comment by iocanel** [comment]
@davidkuster: You'll just have to install the updated version of the plugin in Jenkins.

**Comment by davidkuster** [comment]
Appreciate it. I have not been administering our Jenkins instance but great tip. :)

**Pull request merged**
